import './globals.css'
import '../app/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script';
import 'bootstrap/dist/css/bootstrap.min.css';
import React from 'react';
import Image from 'next/image'
import News from '././components/News'
import Weather from '././components/Weather'
import dynamic from 'next/dynamic';
import Sidebar from '././components/Sidebar'
import Header from '././components/Header'
import Main from '././components/Main'
import Footer from '././components/Footer'
import 'bootstrap/dist/css/bootstrap.min.css';
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <Sidebar />
      <main>
        <div>{children}</div>
      </main>
      <Footer/>
    </body>
      <Script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"></Script>
      <Script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></Script>
    </html>
  )
}
